config/routes.rb
require "monban/constraints/signed_in"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  root  "welcome#index"

  resources :shouts, only: [:create]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "follow" => "following_relationships#create"
      delete "unfollow" => "following_relationships#destroy"
    end
  end
end

app/models/following_relationship.rb
class FollowingRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base
  has_attached_file :photo
  validates_attachment_content_type :photo,
    :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/shout.rb
class Shout < ActiveRecord::Base
  default_scope { order(created_at: :desc) }
  belongs_to :user
  belongs_to :content, polymorphic: true

  delegate :username, to: :user
end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts

  has_many :followed_user_relationships,
    foreign_key: :follower_id,
    class_name: "FollowingRelationship"
  has_many :followed_users,
    through: :followed_user_relationships

  has_many :follower_relationships,
    foreign_key: :followed_user_id,
    class_name: "FollowingRelationship"
  has_many :followers,
    through: :follower_relationships

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  def follow(user)
    followed_users << user
  end

  def following?(user)
    followed_users.where(id: user.id).exists?
  end

  def unfollow(user)
    followed_users.destroy(user)
  end

  def can_follow?(user)
    user.id != id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @dashboard = Dashboard.new(current_user)
  end
end

app/controllers/following_relationships_controller.rb
class FollowingRelationshipsController < ApplicationController
  def create
    user = find_user
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = find_user
    current_user.unfollow(user)
    redirect_to user
  end

  private

  def find_user
    User.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params, email_or_username: %i(email username))

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email_or_username, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  def create
    current_user.shouts.create(shout_params)
    redirect_to dashboard_path
  end

  private

  def shout_params
    { content: build_content }
  end

  def build_content
    params[:shout][:content_type].constantize.new(content_params)
  end

  def content_params
    params[:shout][:content].permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts
  end

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def follow_button(user)
    if current_user.following?(user)
      button_to "Unfollow", unfollow_user_path(user), method: :delete
    elsif current_user.can_follow?(user)
      button_to "Follow", follow_user_path(user)
    end
  end

end

app/views/application/_user_bar.html.erb
<% if signed_in? %>
  Welcome <%= current_user.username %>
  <%= link_to "Sign out", session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_path %>
  <%= link_to "Sign in", new_session_path %>
<% end %>

app/views/dashboards/show.html.erb
<%= form_for Shout.new do |form| %>
  <%= form.fields_for(:content) do |content_form| %>
    <%= content_form.text_field :body, placeholder: "Shout here!" %>
  <% end %>
  <%= form.hidden_field :content_type, value: "TextShout" %>
  <%= form.submit "Shout" %>
<% end %>

<%= form_for Shout.new do |form| %>
  <%= form.fields_for(:content) do |content_form| %>
    <%= content_form.file_field :photo, placeholder: "Shout here!" %>
  <% end %>
  <%= form.hidden_field :content_type, value: "PhotoShout" %>
  <%= form.submit "Shout" %>
<% end %>

<%= render @dashboard.shouts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "user_bar" %>
<%= yield %>

</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= image_tag photo_shout.photo.url %>

app/views/shouts/_shout.html.erb
<%= div_for(shout) do %>
  <%= link_to shout.username, shout.user %>
  <%= time_ago_in_words shout.created_at %> ago
  <%= render shout.content %>
<% end %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= follow_button(@user) %>

<%= render @shouts %>

app/views/welcome/_user_bar.html.erb
  <% if signed_in? %>
    Welcome <%= current_user.username %>
    <%= link_to "Sign out", session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Sign in", new_session_path %>
  <% end %>

app/views/welcome/_user_bar2.html.erb
  <% if signed_in? %>
    Welcome <%= current_user.username %>
    <%= link_to "Sign out", session_path, method: :delete %>
    <% else %>
    <%= link_to "Sign up", new_user_path %>
    <%= link_to "Sign in", new_session_path %>
  <% end %>

app/views/welcome/index.html.erb
Welcome to Shouter